version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/price_tracker
      - EMAIL_ADDRESS=your_email@gmail.com
      - EMAIL_PASSWORD=your_email_password
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: price_tracker
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
